#A make file for the main presentation.

all : PDF PDF_R
PDF: ContaminatedPropertiesAssessment.tex
	pdflatex ContaminatedPropertiesAssessment.tex

PDF_R :
	pdflatex RealitzProcessFlow.tex
	 
clean:
		rm ContaminatedPropertiesAssessment*.out
		rm ContaminatedPropertiesAssessment*.aux
		rm ContaminatedPropertiesAssessment*.lo?
		rm ContaminatedPropertiesAssessment*.toc
