// Generated by Haxe 3.4.7
(function () { "use strict";
var List = function() { };
List.__name__ = true;
Math.__name__ = true;
var Realitz = function() { };
Realitz.__name__ = true;
Realitz.main = function() {
	console.log("Hello Realitz");
	var e = realitz_tezos_rpc_Error.EmptyAnswer;
};
var haxe_ds_Option = { __ename__ : true, __constructs__ : ["Some","None"] };
haxe_ds_Option.Some = function(v) { var $x = ["Some",0,v]; $x.__enum__ = haxe_ds_Option; return $x; };
haxe_ds_Option.None = ["None",1];
haxe_ds_Option.None.__enum__ = haxe_ds_Option;
var haxe_io_Bytes = function() { };
haxe_io_Bytes.__name__ = true;
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var realitz_core_Property = function() { };
realitz_core_Property.__name__ = true;
realitz_core_Property.prototype = {
	Property: function() {
		console.log("Constructing property");
	}
};
var realitz_tezos_rpc_BlockHeader = function() { };
realitz_tezos_rpc_BlockHeader.__name__ = true;
var realitz_tezos_rpc_BlockHeaderWithData = function() { };
realitz_tezos_rpc_BlockHeaderWithData.__name__ = true;
var realitz_tezos_rpc_Method = { __ename__ : true, __constructs__ : ["GET","PUT"] };
realitz_tezos_rpc_Method.GET = ["GET",0];
realitz_tezos_rpc_Method.GET.__enum__ = realitz_tezos_rpc_Method;
realitz_tezos_rpc_Method.PUT = ["PUT",1];
realitz_tezos_rpc_Method.PUT.__enum__ = realitz_tezos_rpc_Method;
var realitz_tezos_rpc_HttpStatusCode = { __ename__ : true, __constructs__ : ["OK","Error"] };
realitz_tezos_rpc_HttpStatusCode.OK = ["OK",0];
realitz_tezos_rpc_HttpStatusCode.OK.__enum__ = realitz_tezos_rpc_HttpStatusCode;
realitz_tezos_rpc_HttpStatusCode.Error = ["Error",1];
realitz_tezos_rpc_HttpStatusCode.Error.__enum__ = realitz_tezos_rpc_HttpStatusCode;
var realitz_tezos_rpc_Error = { __ename__ : true, __constructs__ : ["EmptyAnswer","ConnectionFailed","BadRequest","MethodNotAllowed","UnsupportedMedia","NotAcceptable","UnexpectedStatusCode","UnexpectedContentType","UnexpectedContent","OcamlException"] };
realitz_tezos_rpc_Error.EmptyAnswer = ["EmptyAnswer",0];
realitz_tezos_rpc_Error.EmptyAnswer.__enum__ = realitz_tezos_rpc_Error;
realitz_tezos_rpc_Error.ConnectionFailed = function(message) { var $x = ["ConnectionFailed",1,message]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.BadRequest = function(message) { var $x = ["BadRequest",2,message]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.MethodNotAllowed = function(methodList) { var $x = ["MethodNotAllowed",3,methodList]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnsupportedMedia = function(mediaType) { var $x = ["UnsupportedMedia",4,mediaType]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.NotAcceptable = function(proposed,acceptable) { var $x = ["NotAcceptable",5,proposed,acceptable]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnexpectedStatusCode = function(code,content,mediaType) { var $x = ["UnexpectedStatusCode",6,code,content,mediaType]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnexpectedContentType = function(received,acceptable,body) { var $x = ["UnexpectedContentType",7,received,acceptable,body]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnexpectedContent = function(content,mediaType,error) { var $x = ["UnexpectedContent",8,content,mediaType,error]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.OcamlException = function(exceptionMessage) { var $x = ["OcamlException",9,exceptionMessage]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
String.__name__ = true;
Array.__name__ = true;
Realitz.main();
})();
