// Generated by Haxe 3.4.7
(function () { "use strict";
var List = function() { };
List.__name__ = true;
Math.__name__ = true;
var Realitz = function() { };
Realitz.__name__ = true;
Realitz.main = function() {
	console.log("Hello Realitz");
	var e = realitz_tezos_rpc_Error.EmptyAnswer;
};
var haxe__$Int64__$_$_$Int64 = function() { };
haxe__$Int64__$_$_$Int64.__name__ = true;
var haxe_ds_Option = { __ename__ : true, __constructs__ : ["Some","None"] };
haxe_ds_Option.Some = function(v) { var $x = ["Some",0,v]; $x.__enum__ = haxe_ds_Option; return $x; };
haxe_ds_Option.None = ["None",1];
haxe_ds_Option.None.__enum__ = haxe_ds_Option;
var haxe_io_Bytes = function() { };
haxe_io_Bytes.__name__ = true;
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var realitz_core_Property = function() { };
realitz_core_Property.__name__ = true;
realitz_core_Property.prototype = {
	Property: function() {
		console.log("Constructing property");
	}
};
var realitz_tezos_rpc_BlockHeader = function() { };
realitz_tezos_rpc_BlockHeader.__name__ = true;
var realitz_tezos_rpc_BlockHeaderWithData = function() { };
realitz_tezos_rpc_BlockHeaderWithData.__name__ = true;
var realitz_tezos_rpc_BlockResponse = function() { };
realitz_tezos_rpc_BlockResponse.__name__ = true;
var realitz_tezos_rpc_InjectBlock = function() { };
realitz_tezos_rpc_InjectBlock.__name__ = true;
var realitz_tezos_rpc_InjectOperation = function() { };
realitz_tezos_rpc_InjectOperation.__name__ = true;
var realitz_tezos_rpc_OperationHash = function() { };
realitz_tezos_rpc_OperationHash.__name__ = true;
var realitz_tezos_rpc_Component = function() { };
realitz_tezos_rpc_Component.__name__ = true;
var realitz_tezos_rpc_InjectProtocol = function() { };
realitz_tezos_rpc_InjectProtocol.__name__ = true;
var realitz_tezos_rpc_Bootstrapped = function() { };
realitz_tezos_rpc_Bootstrapped.__name__ = true;
var realitz_tezos_rpc_Fitness = function() { };
realitz_tezos_rpc_Fitness.__name__ = true;
var realitz_tezos_rpc_BlockInformation = function() { };
realitz_tezos_rpc_BlockInformation.__name__ = true;
var realitz_tezos_rpc_IdPoint = function() { };
realitz_tezos_rpc_IdPoint.__name__ = true;
var realitz_tezos_rpc_ConnectionVersion = function() { };
realitz_tezos_rpc_ConnectionVersion.__name__ = true;
var realitz_tezos_rpc_Metadata = function() { };
realitz_tezos_rpc_Metadata.__name__ = true;
var realitz_tezos_rpc_ConnectionInformation = function() { };
realitz_tezos_rpc_ConnectionInformation.__name__ = true;
var realitz_tezos_rpc_PoolEvent = { __ename__ : true, __constructs__ : ["TooFewConnections","TooManyConnections","NewPoint","NewPeer","GCPoints","IncomingConnection","OutgoingConnection","AuthenticationFailed","AcceptingRequest","RejectingRequest","RequestRejected","ConnectionEstablished","SwapRequestReceived","SwapAckReceived","SwapRequestSent","SwapAckSent","SwapRequestIgnored","SwapSuccess","SwapFailure","Disconnection","ExternalDisconnection"] };
realitz_tezos_rpc_PoolEvent.TooFewConnections = ["TooFewConnections",0];
realitz_tezos_rpc_PoolEvent.TooFewConnections.__enum__ = realitz_tezos_rpc_PoolEvent;
realitz_tezos_rpc_PoolEvent.TooManyConnections = ["TooManyConnections",1];
realitz_tezos_rpc_PoolEvent.TooManyConnections.__enum__ = realitz_tezos_rpc_PoolEvent;
realitz_tezos_rpc_PoolEvent.NewPoint = function(point) { var $x = ["NewPoint",2,point]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.NewPeer = function(peer) { var $x = ["NewPeer",3,peer]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.GCPoints = ["GCPoints",4];
realitz_tezos_rpc_PoolEvent.GCPoints.__enum__ = realitz_tezos_rpc_PoolEvent;
realitz_tezos_rpc_PoolEvent.IncomingConnection = function(point) { var $x = ["IncomingConnection",5,point]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.OutgoingConnection = function(point) { var $x = ["OutgoingConnection",6,point]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.AuthenticationFailed = function(point) { var $x = ["AuthenticationFailed",7,point]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.AcceptingRequest = function(point,identifier,peerId) { var $x = ["AcceptingRequest",8,point,identifier,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.RejectingRequest = function(point,identifier,peerId) { var $x = ["RejectingRequest",9,point,identifier,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.RequestRejected = function(point,identifier,peerId) { var $x = ["RequestRejected",10,point,identifier,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.ConnectionEstablished = function(identifier,peer) { var $x = ["ConnectionEstablished",11,identifier,peer]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapRequestReceived = function(source) { var $x = ["SwapRequestReceived",12,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapAckReceived = function(source) { var $x = ["SwapAckReceived",13,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapRequestSent = function(source) { var $x = ["SwapRequestSent",14,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapAckSent = function(source) { var $x = ["SwapAckSent",15,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapRequestIgnored = function(source) { var $x = ["SwapRequestIgnored",16,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapSuccess = function(source) { var $x = ["SwapSuccess",17,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapFailure = function(source) { var $x = ["SwapFailure",18,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.Disconnection = function(peerId) { var $x = ["Disconnection",19,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.ExternalDisconnection = function(peerId) { var $x = ["ExternalDisconnection",20,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
var realitz_tezos_rpc_ConnectionInfo = function() { };
realitz_tezos_rpc_ConnectionInfo.__name__ = true;
var realitz_tezos_rpc_ConnectionMetadata = function() { };
realitz_tezos_rpc_ConnectionMetadata.__name__ = true;
var realitz_tezos_rpc_PeerState = { __ename__ : true, __constructs__ : ["Running","Accepted","Disconnected"] };
realitz_tezos_rpc_PeerState.Running = ["Running",0];
realitz_tezos_rpc_PeerState.Running.__enum__ = realitz_tezos_rpc_PeerState;
realitz_tezos_rpc_PeerState.Accepted = ["Accepted",1];
realitz_tezos_rpc_PeerState.Accepted.__enum__ = realitz_tezos_rpc_PeerState;
realitz_tezos_rpc_PeerState.Disconnected = ["Disconnected",2];
realitz_tezos_rpc_PeerState.Disconnected.__enum__ = realitz_tezos_rpc_PeerState;
var realitz_tezos_rpc_PeerStatistics = function() { };
realitz_tezos_rpc_PeerStatistics.__name__ = true;
var realitz_tezos_rpc_Monitor = function() { };
realitz_tezos_rpc_Monitor.__name__ = true;
var realitz_tezos_rpc_Peer = function() { };
realitz_tezos_rpc_Peer.__name__ = true;
var realitz_tezos_rpc_TestChainStatus = { __ename__ : true, __constructs__ : ["NotRunning","Forking","Running"] };
realitz_tezos_rpc_TestChainStatus.NotRunning = ["NotRunning",0];
realitz_tezos_rpc_TestChainStatus.NotRunning.__enum__ = realitz_tezos_rpc_TestChainStatus;
realitz_tezos_rpc_TestChainStatus.Forking = function(protocol,expiration) { var $x = ["Forking",1,protocol,expiration]; $x.__enum__ = realitz_tezos_rpc_TestChainStatus; return $x; };
realitz_tezos_rpc_TestChainStatus.Running = function(chainId,genesis,protocol,expiration) { var $x = ["Running",2,chainId,genesis,protocol,expiration]; $x.__enum__ = realitz_tezos_rpc_TestChainStatus; return $x; };
var realitz_tezos_rpc_BlockHeaderMetadata = function() { };
realitz_tezos_rpc_BlockHeaderMetadata.__name__ = true;
var realitz_tezos_rpc_Level = function() { };
realitz_tezos_rpc_Level.__name__ = true;
var realitz_tezos_rpc_VotingPeriodKind = { __ename__ : true, __constructs__ : ["Proposal","TestingVote","Testing","PromotionVote"] };
realitz_tezos_rpc_VotingPeriodKind.Proposal = ["Proposal",0];
realitz_tezos_rpc_VotingPeriodKind.Proposal.__enum__ = realitz_tezos_rpc_VotingPeriodKind;
realitz_tezos_rpc_VotingPeriodKind.TestingVote = ["TestingVote",1];
realitz_tezos_rpc_VotingPeriodKind.TestingVote.__enum__ = realitz_tezos_rpc_VotingPeriodKind;
realitz_tezos_rpc_VotingPeriodKind.Testing = ["Testing",2];
realitz_tezos_rpc_VotingPeriodKind.Testing.__enum__ = realitz_tezos_rpc_VotingPeriodKind;
realitz_tezos_rpc_VotingPeriodKind.PromotionVote = ["PromotionVote",3];
realitz_tezos_rpc_VotingPeriodKind.PromotionVote.__enum__ = realitz_tezos_rpc_VotingPeriodKind;
var realitz_tezos_rpc_ContractKind = { __ename__ : true, __constructs__ : ["Freezer"] };
realitz_tezos_rpc_ContractKind.Freezer = ["Freezer",0];
realitz_tezos_rpc_ContractKind.Freezer.__enum__ = realitz_tezos_rpc_ContractKind;
var realitz_tezos_rpc_BalanceUpdate = { __ename__ : true, __constructs__ : ["Contract","Rewards","Fees","Deposits"] };
realitz_tezos_rpc_BalanceUpdate.Contract = function(contractId,change) { var $x = ["Contract",0,contractId,change]; $x.__enum__ = realitz_tezos_rpc_BalanceUpdate; return $x; };
realitz_tezos_rpc_BalanceUpdate.Rewards = function(kind,deletage,level,change) { var $x = ["Rewards",1,kind,deletage,level,change]; $x.__enum__ = realitz_tezos_rpc_BalanceUpdate; return $x; };
realitz_tezos_rpc_BalanceUpdate.Fees = function(kind,delegate,level,change) { var $x = ["Fees",2,kind,delegate,level,change]; $x.__enum__ = realitz_tezos_rpc_BalanceUpdate; return $x; };
realitz_tezos_rpc_BalanceUpdate.Deposits = function(kind,delegate,level,change) { var $x = ["Deposits",3,kind,delegate,level,change]; $x.__enum__ = realitz_tezos_rpc_BalanceUpdate; return $x; };
var realitz_tezos_rpc_Signature = function() { };
realitz_tezos_rpc_Signature.__name__ = true;
var realitz_tezos_rpc_InlinedEndorsement = function() { };
realitz_tezos_rpc_InlinedEndorsement.__name__ = true;
var realitz_tezos_rpc_EndorsementKind = { __ename__ : true, __constructs__ : ["Endorsement"] };
realitz_tezos_rpc_EndorsementKind.Endorsement = ["Endorsement",0];
realitz_tezos_rpc_EndorsementKind.Endorsement.__enum__ = realitz_tezos_rpc_EndorsementKind;
var realitz_tezos_rpc_InlinedEndorsementContent = function() { };
realitz_tezos_rpc_InlinedEndorsementContent.__name__ = true;
var realitz_tezos_rpc_BlockRequestView = function() { };
realitz_tezos_rpc_BlockRequestView.__name__ = true;
var realitz_tezos_rpc_BlockRequest = function() { };
realitz_tezos_rpc_BlockRequest.__name__ = true;
var realitz_tezos_rpc_Backlog = function() { };
realitz_tezos_rpc_Backlog.__name__ = true;
var realitz_tezos_rpc_WorkerStateEvent = { __ename__ : true, __constructs__ : ["Debug","ValidationSuccess","ValidationFailure"] };
realitz_tezos_rpc_WorkerStateEvent.Debug = function(message) { var $x = ["Debug",0,message]; $x.__enum__ = realitz_tezos_rpc_WorkerStateEvent; return $x; };
realitz_tezos_rpc_WorkerStateEvent.ValidationSuccess = function(view,status) { var $x = ["ValidationSuccess",1,view,status]; $x.__enum__ = realitz_tezos_rpc_WorkerStateEvent; return $x; };
realitz_tezos_rpc_WorkerStateEvent.ValidationFailure = function(view,status,errors) { var $x = ["ValidationFailure",2,view,status,errors]; $x.__enum__ = realitz_tezos_rpc_WorkerStateEvent; return $x; };
var realitz_tezos_rpc_BlockValidator = function() { };
realitz_tezos_rpc_BlockValidator.__name__ = true;
var realitz_tezos_rpc_Error = { __ename__ : true, __constructs__ : ["EmptyAnswer","ConnectionFailed","BadRequest","MethodNotAllowed","UnsupportedMedia","NotAcceptable","UnexpectedStatusCode","UnexpectedContentType","UnexpectedContent","OcamlException"] };
realitz_tezos_rpc_Error.EmptyAnswer = ["EmptyAnswer",0];
realitz_tezos_rpc_Error.EmptyAnswer.__enum__ = realitz_tezos_rpc_Error;
realitz_tezos_rpc_Error.ConnectionFailed = function(message) { var $x = ["ConnectionFailed",1,message]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.BadRequest = function(message) { var $x = ["BadRequest",2,message]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.MethodNotAllowed = function(methodList) { var $x = ["MethodNotAllowed",3,methodList]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnsupportedMedia = function(mediaType) { var $x = ["UnsupportedMedia",4,mediaType]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.NotAcceptable = function(proposed,acceptable) { var $x = ["NotAcceptable",5,proposed,acceptable]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnexpectedStatusCode = function(code,content,mediaType) { var $x = ["UnexpectedStatusCode",6,code,content,mediaType]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnexpectedContentType = function(received,acceptable,body) { var $x = ["UnexpectedContentType",7,received,acceptable,body]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnexpectedContent = function(content,mediaType,error) { var $x = ["UnexpectedContent",8,content,mediaType,error]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.OcamlException = function(exceptionMessage) { var $x = ["OcamlException",9,exceptionMessage]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
var realitz_tezos_rpc_MichelsonV1Expression = { __ename__ : true, __constructs__ : ["IntExpression","StringExpression","ByteExpression","MichelsonV1Expressions","PrimitiveExpression"] };
realitz_tezos_rpc_MichelsonV1Expression.IntExpression = function(exp) { var $x = ["IntExpression",0,exp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Expression; return $x; };
realitz_tezos_rpc_MichelsonV1Expression.StringExpression = function(exp) { var $x = ["StringExpression",1,exp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Expression; return $x; };
realitz_tezos_rpc_MichelsonV1Expression.ByteExpression = function(exp) { var $x = ["ByteExpression",2,exp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Expression; return $x; };
realitz_tezos_rpc_MichelsonV1Expression.MichelsonV1Expressions = function(exps) { var $x = ["MichelsonV1Expressions",3,exps]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Expression; return $x; };
realitz_tezos_rpc_MichelsonV1Expression.PrimitiveExpression = function(prim,args,annotations) { var $x = ["PrimitiveExpression",4,prim,args,annotations]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Expression; return $x; };
var realitz_tezos_rpc_MichelsonV1Primitive = { __ename__ : true, __constructs__ : ["ADD","LE","UPDATE","Amount","Drop","LEFT","Timestamp","Concat","Nat","Bytes","MOr","CONTRACT","Swap","Mem","Lambda","Operation","EmptySet","Unit","MString","MCompare","MLambda","LOOP","ELT","ImplicitAccount","NONE","Signature","SetVal","Mutez","Blake2B","SHA256","ITER","MBool","MMap","IFCons","LSR","SetDelegate","Storage","XOR","CDR","TransferTokens","MSome","MFalse","SHA512","CheckSignature","Balance","IsNat","MCode","MAND","EmptyMap","CreateContract","HashKey","Pair","LoopLeft","Rename","IFLeft","FailWith","GT","Key","MGet","MList","EQ","Now","KeyHash","DUP","MOption","BigMap","Sender","MInt","Left","Self","MIf","LSL","MOR","IFNone","CAR","CreateAccount","Source","StepsToQuota","Address","EDiv","Sub","Cast","Mul","Exec","Nil","None","Cons","NEQ","NEG","LT","GE","Push","ABS","Contract"] };
realitz_tezos_rpc_MichelsonV1Primitive.ADD = function(disp) { var $x = ["ADD",0,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.LE = function(disp) { var $x = ["LE",1,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.UPDATE = function(disp) { var $x = ["UPDATE",2,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Amount = function(disp) { var $x = ["Amount",3,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Drop = function(disp) { var $x = ["Drop",4,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.LEFT = function(disp) { var $x = ["LEFT",5,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Timestamp = function(disp) { var $x = ["Timestamp",6,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Concat = function(disp) { var $x = ["Concat",7,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Nat = function(disp) { var $x = ["Nat",8,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Bytes = function(disp) { var $x = ["Bytes",9,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MOr = function(disp) { var $x = ["MOr",10,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.CONTRACT = function(disp) { var $x = ["CONTRACT",11,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Swap = function(disp) { var $x = ["Swap",12,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Mem = function(disp) { var $x = ["Mem",13,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Lambda = function(disp) { var $x = ["Lambda",14,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Operation = function(disp) { var $x = ["Operation",15,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.EmptySet = function(disp) { var $x = ["EmptySet",16,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Unit = function(disp) { var $x = ["Unit",17,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MString = function(disp) { var $x = ["MString",18,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MCompare = function(disp) { var $x = ["MCompare",19,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MLambda = function(disp) { var $x = ["MLambda",20,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.LOOP = function(disp) { var $x = ["LOOP",21,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.ELT = function(disp) { var $x = ["ELT",22,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.ImplicitAccount = function(disp) { var $x = ["ImplicitAccount",23,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.NONE = function(disp) { var $x = ["NONE",24,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Signature = function(disp) { var $x = ["Signature",25,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.SetVal = function(disp) { var $x = ["SetVal",26,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Mutez = function(disp) { var $x = ["Mutez",27,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Blake2B = function(disp) { var $x = ["Blake2B",28,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.SHA256 = function(disp) { var $x = ["SHA256",29,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.ITER = function(disp) { var $x = ["ITER",30,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MBool = function(disp) { var $x = ["MBool",31,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MMap = function(disp) { var $x = ["MMap",32,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.IFCons = function(disp) { var $x = ["IFCons",33,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.LSR = function(disp) { var $x = ["LSR",34,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.SetDelegate = function(disp) { var $x = ["SetDelegate",35,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Storage = function(disp) { var $x = ["Storage",36,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.XOR = function(disp) { var $x = ["XOR",37,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.CDR = function(disp) { var $x = ["CDR",38,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.TransferTokens = function(disp) { var $x = ["TransferTokens",39,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MSome = function(disp) { var $x = ["MSome",40,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MFalse = function(disp) { var $x = ["MFalse",41,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.SHA512 = function(disp) { var $x = ["SHA512",42,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.CheckSignature = function(disp) { var $x = ["CheckSignature",43,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Balance = function(disp) { var $x = ["Balance",44,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.IsNat = function(disp) { var $x = ["IsNat",45,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MCode = function(disp) { var $x = ["MCode",46,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MAND = function(disp) { var $x = ["MAND",47,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.EmptyMap = function(disp) { var $x = ["EmptyMap",48,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.CreateContract = function(disp) { var $x = ["CreateContract",49,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.HashKey = function(disp) { var $x = ["HashKey",50,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Pair = function(disp) { var $x = ["Pair",51,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.LoopLeft = function(disp) { var $x = ["LoopLeft",52,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Rename = function(disp) { var $x = ["Rename",53,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.IFLeft = function(disp) { var $x = ["IFLeft",54,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.FailWith = function(disp) { var $x = ["FailWith",55,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.GT = function(disp) { var $x = ["GT",56,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Key = function(disp) { var $x = ["Key",57,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MGet = function(disp) { var $x = ["MGet",58,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MList = function(disp) { var $x = ["MList",59,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.EQ = function(disp) { var $x = ["EQ",60,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Now = function(disp) { var $x = ["Now",61,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.KeyHash = function(disp) { var $x = ["KeyHash",62,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.DUP = function(disp) { var $x = ["DUP",63,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MOption = function(disp) { var $x = ["MOption",64,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.BigMap = function(disp) { var $x = ["BigMap",65,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Sender = function(disp) { var $x = ["Sender",66,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MInt = function(disp) { var $x = ["MInt",67,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Left = function(disp) { var $x = ["Left",68,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Self = function(disp) { var $x = ["Self",69,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MIf = function(disp) { var $x = ["MIf",70,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.LSL = function(disp) { var $x = ["LSL",71,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.MOR = function(disp) { var $x = ["MOR",72,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.IFNone = function(disp) { var $x = ["IFNone",73,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.CAR = function(disp) { var $x = ["CAR",74,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.CreateAccount = function(disp) { var $x = ["CreateAccount",75,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Source = function(disp) { var $x = ["Source",76,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.StepsToQuota = function(disp) { var $x = ["StepsToQuota",77,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Address = function(disp) { var $x = ["Address",78,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.EDiv = function(disp) { var $x = ["EDiv",79,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Sub = function(disp) { var $x = ["Sub",80,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Cast = function(disp) { var $x = ["Cast",81,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Mul = function(disp) { var $x = ["Mul",82,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Exec = function(disp) { var $x = ["Exec",83,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Nil = function(disp) { var $x = ["Nil",84,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.None = function(disp) { var $x = ["None",85,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Cons = function(disp) { var $x = ["Cons",86,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.NEQ = function(disp) { var $x = ["NEQ",87,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.NEG = function(disp) { var $x = ["NEG",88,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.LT = function(disp) { var $x = ["LT",89,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.GE = function(disp) { var $x = ["GE",90,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Push = function(disp) { var $x = ["Push",91,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.ABS = function(disp) { var $x = ["ABS",92,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
realitz_tezos_rpc_MichelsonV1Primitive.Contract = function(disp) { var $x = ["Contract",93,disp]; $x.__enum__ = realitz_tezos_rpc_MichelsonV1Primitive; return $x; };
var realitz_tezos_rpc_ProtocolHash = function() { };
realitz_tezos_rpc_ProtocolHash.__name__ = true;
var realitz_tezos_rpc_ContextHash = function() { };
realitz_tezos_rpc_ContextHash.__name__ = true;
var realitz_tezos_rpc_Method = { __ename__ : true, __constructs__ : ["GET","POST","DELETE","PUT","PATCH"] };
realitz_tezos_rpc_Method.GET = ["GET",0];
realitz_tezos_rpc_Method.GET.__enum__ = realitz_tezos_rpc_Method;
realitz_tezos_rpc_Method.POST = ["POST",1];
realitz_tezos_rpc_Method.POST.__enum__ = realitz_tezos_rpc_Method;
realitz_tezos_rpc_Method.DELETE = ["DELETE",2];
realitz_tezos_rpc_Method.DELETE.__enum__ = realitz_tezos_rpc_Method;
realitz_tezos_rpc_Method.PUT = ["PUT",3];
realitz_tezos_rpc_Method.PUT.__enum__ = realitz_tezos_rpc_Method;
realitz_tezos_rpc_Method.PATCH = ["PATCH",4];
realitz_tezos_rpc_Method.PATCH.__enum__ = realitz_tezos_rpc_Method;
var realitz_tezos_rpc_HttpStatusCode = { __ename__ : true, __constructs__ : ["OK","Error"] };
realitz_tezos_rpc_HttpStatusCode.OK = ["OK",0];
realitz_tezos_rpc_HttpStatusCode.OK.__enum__ = realitz_tezos_rpc_HttpStatusCode;
realitz_tezos_rpc_HttpStatusCode.Error = ["Error",1];
realitz_tezos_rpc_HttpStatusCode.Error.__enum__ = realitz_tezos_rpc_HttpStatusCode;
var realitz_tezos_rpc_RPCServiceError = { __ename__ : true, __constructs__ : ["Exception","Canceled"] };
realitz_tezos_rpc_RPCServiceError.Exception = function(message) { var $x = ["Exception",0,message]; $x.__enum__ = realitz_tezos_rpc_RPCServiceError; return $x; };
realitz_tezos_rpc_RPCServiceError.Canceled = ["Canceled",1];
realitz_tezos_rpc_RPCServiceError.Canceled.__enum__ = realitz_tezos_rpc_RPCServiceError;
var realitz_tezos_rpc_Answer = { __ename__ : true, __constructs__ : ["Ok","Created","NoContent","Unauthorized","Forbidden","NotFound","Conflict","Error"] };
realitz_tezos_rpc_Answer.Ok = function(code) { var $x = ["Ok",0,code]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Created = function(code) { var $x = ["Created",1,code]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.NoContent = function(code) { var $x = ["NoContent",2,code]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Unauthorized = function(errorCode) { var $x = ["Unauthorized",3,errorCode]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Forbidden = function(errorCode) { var $x = ["Forbidden",4,errorCode]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.NotFound = function(errorCode) { var $x = ["NotFound",5,errorCode]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Conflict = function(errorCode) { var $x = ["Conflict",6,errorCode]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Error = function(error) { var $x = ["Error",7,error]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
var realitz_tezos_rpc_BlockHash = function() { };
realitz_tezos_rpc_BlockHash.__name__ = true;
var realitz_tezos_rpc_ChainId = function() { };
realitz_tezos_rpc_ChainId.__name__ = true;
var realitz_tezos_rpc_PublicKey = function() { };
realitz_tezos_rpc_PublicKey.__name__ = true;
var realitz_tezos_rpc_WorkerStatus = { __ename__ : true, __constructs__ : ["Launching","Running","Closing","Closed"] };
realitz_tezos_rpc_WorkerStatus.Launching = function(timestamp) { var $x = ["Launching",0,timestamp]; $x.__enum__ = realitz_tezos_rpc_WorkerStatus; return $x; };
realitz_tezos_rpc_WorkerStatus.Running = function(timestamp) { var $x = ["Running",1,timestamp]; $x.__enum__ = realitz_tezos_rpc_WorkerStatus; return $x; };
realitz_tezos_rpc_WorkerStatus.Closing = function(start,end) { var $x = ["Closing",2,start,end]; $x.__enum__ = realitz_tezos_rpc_WorkerStatus; return $x; };
realitz_tezos_rpc_WorkerStatus.Closed = function(start,end,errors) { var $x = ["Closed",3,start,end,errors]; $x.__enum__ = realitz_tezos_rpc_WorkerStatus; return $x; };
var realitz_tezos_rpc_RequestStatus = { __ename__ : true, __constructs__ : ["Pushed","Treated","Completed"] };
realitz_tezos_rpc_RequestStatus.Pushed = function(timestamp) { var $x = ["Pushed",0,timestamp]; $x.__enum__ = realitz_tezos_rpc_RequestStatus; return $x; };
realitz_tezos_rpc_RequestStatus.Treated = function(timestamp) { var $x = ["Treated",1,timestamp]; $x.__enum__ = realitz_tezos_rpc_RequestStatus; return $x; };
realitz_tezos_rpc_RequestStatus.Completed = function(timestamp) { var $x = ["Completed",2,timestamp]; $x.__enum__ = realitz_tezos_rpc_RequestStatus; return $x; };
String.__name__ = true;
Array.__name__ = true;
Realitz.main();
})();
