// Generated by Haxe 3.4.7
(function () { "use strict";
var List = function() { };
List.__name__ = true;
Math.__name__ = true;
var Realitz = function() { };
Realitz.__name__ = true;
Realitz.main = function() {
	console.log("Hello Realitz");
	var e = realitz_tezos_rpc_Error.EmptyAnswer;
};
var haxe__$Int64__$_$_$Int64 = function() { };
haxe__$Int64__$_$_$Int64.__name__ = true;
var haxe_ds_Option = { __ename__ : true, __constructs__ : ["Some","None"] };
haxe_ds_Option.Some = function(v) { var $x = ["Some",0,v]; $x.__enum__ = haxe_ds_Option; return $x; };
haxe_ds_Option.None = ["None",1];
haxe_ds_Option.None.__enum__ = haxe_ds_Option;
var haxe_io_Bytes = function() { };
haxe_io_Bytes.__name__ = true;
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var realitz_core_Property = function() { };
realitz_core_Property.__name__ = true;
realitz_core_Property.prototype = {
	Property: function() {
		console.log("Constructing property");
	}
};
var realitz_tezos_rpc_BlockHeader = function() { };
realitz_tezos_rpc_BlockHeader.__name__ = true;
var realitz_tezos_rpc_BlockHeaderWithData = function() { };
realitz_tezos_rpc_BlockHeaderWithData.__name__ = true;
var realitz_tezos_rpc_BlockHash = function() { };
realitz_tezos_rpc_BlockHash.__name__ = true;
var realitz_tezos_rpc_ChainId = function() { };
realitz_tezos_rpc_ChainId.__name__ = true;
var realitz_tezos_rpc_BlockResponse = function() { };
realitz_tezos_rpc_BlockResponse.__name__ = true;
var realitz_tezos_rpc_InjectBlock = function() { };
realitz_tezos_rpc_InjectBlock.__name__ = true;
var realitz_tezos_rpc_InjectOperation = function() { };
realitz_tezos_rpc_InjectOperation.__name__ = true;
var realitz_tezos_rpc_OperationHash = function() { };
realitz_tezos_rpc_OperationHash.__name__ = true;
var realitz_tezos_rpc_Component = function() { };
realitz_tezos_rpc_Component.__name__ = true;
var realitz_tezos_rpc_ProtocolHash = function() { };
realitz_tezos_rpc_ProtocolHash.__name__ = true;
var realitz_tezos_rpc_ContextHash = function() { };
realitz_tezos_rpc_ContextHash.__name__ = true;
var realitz_tezos_rpc_InjectProtocol = function() { };
realitz_tezos_rpc_InjectProtocol.__name__ = true;
var realitz_tezos_rpc_Bootstrapped = function() { };
realitz_tezos_rpc_Bootstrapped.__name__ = true;
var realitz_tezos_rpc_Fitness = function() { };
realitz_tezos_rpc_Fitness.__name__ = true;
var realitz_tezos_rpc_PublicKey = function() { };
realitz_tezos_rpc_PublicKey.__name__ = true;
var realitz_tezos_rpc_BlockInformation = function() { };
realitz_tezos_rpc_BlockInformation.__name__ = true;
var realitz_tezos_rpc_IdPoint = function() { };
realitz_tezos_rpc_IdPoint.__name__ = true;
var realitz_tezos_rpc_ConnectionVersion = function() { };
realitz_tezos_rpc_ConnectionVersion.__name__ = true;
var realitz_tezos_rpc_Metadata = function() { };
realitz_tezos_rpc_Metadata.__name__ = true;
var realitz_tezos_rpc_ConnectionInformation = function() { };
realitz_tezos_rpc_ConnectionInformation.__name__ = true;
var realitz_tezos_rpc_PoolEvent = { __ename__ : true, __constructs__ : ["TooFewConnections","TooManyConnections","NewPoint","NewPeer","GCPoints","IncomingConnection","OutgoingConnection","AuthenticationFailed","AcceptingRequest","RejectingRequest","RequestRejected","ConnectionEstablished","SwapRequestReceived","SwapAckReceived","SwapRequestSent","SwapAckSent","SwapRequestIgnored","SwapSuccess","SwapFailure","Disconnection","ExternalDisconnection"] };
realitz_tezos_rpc_PoolEvent.TooFewConnections = ["TooFewConnections",0];
realitz_tezos_rpc_PoolEvent.TooFewConnections.__enum__ = realitz_tezos_rpc_PoolEvent;
realitz_tezos_rpc_PoolEvent.TooManyConnections = ["TooManyConnections",1];
realitz_tezos_rpc_PoolEvent.TooManyConnections.__enum__ = realitz_tezos_rpc_PoolEvent;
realitz_tezos_rpc_PoolEvent.NewPoint = function(point) { var $x = ["NewPoint",2,point]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.NewPeer = function(peer) { var $x = ["NewPeer",3,peer]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.GCPoints = ["GCPoints",4];
realitz_tezos_rpc_PoolEvent.GCPoints.__enum__ = realitz_tezos_rpc_PoolEvent;
realitz_tezos_rpc_PoolEvent.IncomingConnection = function(point) { var $x = ["IncomingConnection",5,point]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.OutgoingConnection = function(point) { var $x = ["OutgoingConnection",6,point]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.AuthenticationFailed = function(point) { var $x = ["AuthenticationFailed",7,point]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.AcceptingRequest = function(point,identifier,peerId) { var $x = ["AcceptingRequest",8,point,identifier,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.RejectingRequest = function(point,identifier,peerId) { var $x = ["RejectingRequest",9,point,identifier,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.RequestRejected = function(point,identifier,peerId) { var $x = ["RequestRejected",10,point,identifier,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.ConnectionEstablished = function(identifier,peer) { var $x = ["ConnectionEstablished",11,identifier,peer]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapRequestReceived = function(source) { var $x = ["SwapRequestReceived",12,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapAckReceived = function(source) { var $x = ["SwapAckReceived",13,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapRequestSent = function(source) { var $x = ["SwapRequestSent",14,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapAckSent = function(source) { var $x = ["SwapAckSent",15,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapRequestIgnored = function(source) { var $x = ["SwapRequestIgnored",16,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapSuccess = function(source) { var $x = ["SwapSuccess",17,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.SwapFailure = function(source) { var $x = ["SwapFailure",18,source]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.Disconnection = function(peerId) { var $x = ["Disconnection",19,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
realitz_tezos_rpc_PoolEvent.ExternalDisconnection = function(peerId) { var $x = ["ExternalDisconnection",20,peerId]; $x.__enum__ = realitz_tezos_rpc_PoolEvent; return $x; };
var realitz_tezos_rpc_Error = { __ename__ : true, __constructs__ : ["EmptyAnswer","ConnectionFailed","BadRequest","MethodNotAllowed","UnsupportedMedia","NotAcceptable","UnexpectedStatusCode","UnexpectedContentType","UnexpectedContent","OcamlException"] };
realitz_tezos_rpc_Error.EmptyAnswer = ["EmptyAnswer",0];
realitz_tezos_rpc_Error.EmptyAnswer.__enum__ = realitz_tezos_rpc_Error;
realitz_tezos_rpc_Error.ConnectionFailed = function(message) { var $x = ["ConnectionFailed",1,message]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.BadRequest = function(message) { var $x = ["BadRequest",2,message]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.MethodNotAllowed = function(methodList) { var $x = ["MethodNotAllowed",3,methodList]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnsupportedMedia = function(mediaType) { var $x = ["UnsupportedMedia",4,mediaType]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.NotAcceptable = function(proposed,acceptable) { var $x = ["NotAcceptable",5,proposed,acceptable]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnexpectedStatusCode = function(code,content,mediaType) { var $x = ["UnexpectedStatusCode",6,code,content,mediaType]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnexpectedContentType = function(received,acceptable,body) { var $x = ["UnexpectedContentType",7,received,acceptable,body]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.UnexpectedContent = function(content,mediaType,error) { var $x = ["UnexpectedContent",8,content,mediaType,error]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
realitz_tezos_rpc_Error.OcamlException = function(exceptionMessage) { var $x = ["OcamlException",9,exceptionMessage]; $x.__enum__ = realitz_tezos_rpc_Error; return $x; };
var realitz_tezos_rpc_Method = { __ename__ : true, __constructs__ : ["GET","POST","DELETE","PUT","PATCH"] };
realitz_tezos_rpc_Method.GET = ["GET",0];
realitz_tezos_rpc_Method.GET.__enum__ = realitz_tezos_rpc_Method;
realitz_tezos_rpc_Method.POST = ["POST",1];
realitz_tezos_rpc_Method.POST.__enum__ = realitz_tezos_rpc_Method;
realitz_tezos_rpc_Method.DELETE = ["DELETE",2];
realitz_tezos_rpc_Method.DELETE.__enum__ = realitz_tezos_rpc_Method;
realitz_tezos_rpc_Method.PUT = ["PUT",3];
realitz_tezos_rpc_Method.PUT.__enum__ = realitz_tezos_rpc_Method;
realitz_tezos_rpc_Method.PATCH = ["PATCH",4];
realitz_tezos_rpc_Method.PATCH.__enum__ = realitz_tezos_rpc_Method;
var realitz_tezos_rpc_HttpStatusCode = { __ename__ : true, __constructs__ : ["OK","Error"] };
realitz_tezos_rpc_HttpStatusCode.OK = ["OK",0];
realitz_tezos_rpc_HttpStatusCode.OK.__enum__ = realitz_tezos_rpc_HttpStatusCode;
realitz_tezos_rpc_HttpStatusCode.Error = ["Error",1];
realitz_tezos_rpc_HttpStatusCode.Error.__enum__ = realitz_tezos_rpc_HttpStatusCode;
var realitz_tezos_rpc_RPCServiceError = { __ename__ : true, __constructs__ : ["Exception","Canceled"] };
realitz_tezos_rpc_RPCServiceError.Exception = function(message) { var $x = ["Exception",0,message]; $x.__enum__ = realitz_tezos_rpc_RPCServiceError; return $x; };
realitz_tezos_rpc_RPCServiceError.Canceled = ["Canceled",1];
realitz_tezos_rpc_RPCServiceError.Canceled.__enum__ = realitz_tezos_rpc_RPCServiceError;
var realitz_tezos_rpc_Answer = { __ename__ : true, __constructs__ : ["Ok","Created","NoContent","Unauthorized","Forbidden","NotFound","Conflict","Error"] };
realitz_tezos_rpc_Answer.Ok = function(code) { var $x = ["Ok",0,code]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Created = function(code) { var $x = ["Created",1,code]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.NoContent = function(code) { var $x = ["NoContent",2,code]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Unauthorized = function(errorCode) { var $x = ["Unauthorized",3,errorCode]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Forbidden = function(errorCode) { var $x = ["Forbidden",4,errorCode]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.NotFound = function(errorCode) { var $x = ["NotFound",5,errorCode]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Conflict = function(errorCode) { var $x = ["Conflict",6,errorCode]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
realitz_tezos_rpc_Answer.Error = function(error) { var $x = ["Error",7,error]; $x.__enum__ = realitz_tezos_rpc_Answer; return $x; };
String.__name__ = true;
Array.__name__ = true;
Realitz.main();
})();
